### ISSUE TITLE
Chrome script does not work

### ISSUE THREAD

**Issue by tuxinaut** [ludios/nixos-playwright#2]
The `Chromium` script does not work anymore, because it expects the `google-chrome-unstable` package to be installed. `NixOS` does not offer this package anymore neither for `20.09` nor for `21.05` (see [NixOS search - google-chrome](https://search.nixos.org/packages?query=google-chrome)).

Only those packages are available:

* google-chrome
* google-chrome-dev
* google-chrome-beta

I changed the expected package in the script to `google-chrome-beta` and the script worked as expected.

Shall I create a **pull request** to fix this problem?

**Comment by ivan** [comment]
Thanks for the report. Sure, I will take that PR if playwright is working with it.

**Comment by tuxinaut** [comment]
ACK; I'm going to create the pull request soonish.

**Comment by ivan** [comment]
I believe the comment at the top of the script was just misleading; the package is `google-chrome-dev` but it installs a `google-chrome-unstable` binary. I adjusted the comment. Let me know if there is still an issue.
