### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by stewit** [ludios/nixos-playwright#6]
Hello,

thanks for your patch scripts!

Would you consider to add a (hopefully free ;-) ) license here in order to make it possible to use them (or variants of them) in other projects?

Thanks in advance!

**Comment by ivan** [comment]
I believed that these scripts were useful only before I figured out that I could tell puppeteer and playwright to use the already-patched-by-nixpkgs `google-chrome-dev` (executable `google-chrome-unstable`). Is patching the playwright chromium using these scripts any better than doing that? AFAIK only the chromium script here works. I might add a license if this is actually still better than using a chromium/chrome from nixpkgs.

**Comment by stewit** [comment]
Ah, I didn't know that! Can you give me a hint how to configure playwright to use this executable?

**Comment by ivan** [comment]
I added a license in https://github.com/ludios/nixos-playwright/commit/1129343bac34002801d5478e86378feb16fa8f34, but I am archiving this repo as I have no use for it after switching to google-chrome-unstable.

`chromium.launch` has a `launchOpts` with an `executablePath` property.

I've sometimes had to patch projects to get their playwright to use a custom executable.

```bash
# For the SvelteKit tests and other things that use playwright.
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
# playwright doesn't support this out of the box; we patch things to use this env var
export PLAYWRIGHT_EXECUTABLE_PATH_CHROMIUM=/run/current-system/sw/bin/google-chrome-unstable
```

e.g. my old patch for svelte/kit:

```patch
diff --git a/packages/adapter-static/test/utils.js b/packages/adapter-static/test/utils.js
index 53ea9f0f..b4d58e66 100644
--- a/packages/adapter-static/test/utils.js
+++ b/packages/adapter-static/test/utils.js
@@ -48,7 +48,11 @@ export function run(app, callback) {
            context.server = await create_server(context.port, handler);

            context.base = `http://localhost:${context.port}`;
-           context.browser = await chromium.launch();
+           const launchOpts = Object.create(null);
+           if (process.env.PLAYWRIGHT_EXECUTABLE_PATH_CHROMIUM) {
+               launchOpts.executablePath = process.env.PLAYWRIGHT_EXECUTABLE_PATH_CHROMIUM;
+           }
+           context.browser = await chromium.launch(launchOpts);
            context.page = await context.browser.newPage();
        } catch (e) {
            // TODO remove unnecessary try-catch https://github.com/lukeed/uvu/pull/61
--
2.36.0
```
